apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: app_code_image
  newName: ghcr.io/scubbo/full-demo-app
  newTag: 96d431022ba652b3731fef18eb5d9e466183611f

resources:
- deployment.yaml
- ingress.yaml
- service.yaml
