apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: app_code_image
    newName: ghcr.io/scubbo/full-demo-app
    newTag: 

resources:
- deployment.yaml
- ingress.yaml
- service.yaml